# Generated by Django 4.0.2 on 2022-02-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_city_posts_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.city'),
        ),
    ]
