# Generated by Django 4.0.2 on 2022-02-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_user_alter_profile_posts_and_more'),
        ('main_app', '0009_alter_post_city'),
    ]

    operations = [
    ]
